# Describes the format for available Yamaha (YNCA) services

send_raw_ynca:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: yamaha_ynca
    raw_data:
      example: "@MAIN:INP=HDMI3"
      required: true
      selector:
        text:
          multiline: true

store_preset:
  target:
    entity:
      integration: yamaha_ynca
      domain: media_player
  fields:
    preset_id:
      example: "12"
      required: true
      selector:
        number:
          min: 1
          max: 40
          mode: box